name: Keep Supabase Awake

on:
  schedule:
    # This runs at 00:00 every Monday and Thursday (twice a week)
    - cron: '0 0 * * 1,4'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API to Keep Supabase Awake
        run: |
          curl -X GET "${{ secrets.API_URL }}" \
          --fail \
          --silent \
          --show-error
